"""initial schema

Revision ID: b6441fc57f74
Revises: 
Create Date: 2026-09-26 15:48:58.203628
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b6441fc57f74'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'market', name='uq_securities_code_market')
    )
    op.create_index('ix_securities_name', 'securities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('ix_accounts_user_id_name', 'accounts', ['user_id', 'name'], unique=False)
    op.create_table('dividend_plans',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('per_share', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'payment_date', name='uq_dividend_plans_security_payment')
    )
    op.create_index('ix_dividend_plans_payment_date', 'dividend_plans', ['payment_date'], unique=False)
    op.create_index('ix_dividend_plans_security_id', 'dividend_plans', ['security_id'], unique=False)
    op.create_table('dividends',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('per_share', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'received')", name='ck_dividends_status_valid'),
    sa.CheckConstraint('amount >= 0', name='ck_dividends_amount_non_negative'),
    sa.CheckConstraint('per_share >= 0', name='ck_dividends_per_share_non_negative'),
    sa.CheckConstraint('shares >= 0', name='ck_dividends_shares_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividends_account_payment_date', 'dividends', ['account_id', 'payment_date'], unique=False)
    op.create_index('ix_dividends_payment_date', 'dividends', ['payment_date'], unique=False)
    op.create_index('ix_dividends_security_id', 'dividends', ['security_id'], unique=False)
    op.create_table('holdings',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', name='uq_holdings_account_security')
    )
    op.create_index('ix_holdings_account_id', 'holdings', ['account_id'], unique=False)
    op.create_index('ix_holdings_security_id', 'holdings', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_holdings_security_id', table_name='holdings')
    op.drop_index('ix_holdings_account_id', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('ix_dividends_security_id', table_name='dividends')
    op.drop_index('ix_dividends_payment_date', table_name='dividends')
    op.drop_index('ix_dividends_account_payment_date', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index('ix_dividend_plans_security_id', table_name='dividend_plans')
    op.drop_index('ix_dividend_plans_payment_date', table_name='dividend_plans')
    op.drop_table('dividend_plans')
    op.drop_index('ix_accounts_user_id_name', table_name='accounts')
    op.drop_index('ix_accounts_user_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_securities_name', table_name='securities')
    op.drop_table('securities')
    # ### end Alembic commands ###
